
name: CI

permissions:
  id-token: write
  contents: read

on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots package
      - name: Upload jar
        uses: actions/upload-artifact@v3
        with:
          name: project_jar
          path: ${{ github.workspace }}/target/newsapi-0.0.1-SNAPSHOT.jar
  docker:
    runs-on: ubuntu-18.04
    needs: [ test ]
    env:
      REPO: ${{ secrets.DOCKER_REPO }}
    steps:
      - uses: actions/checkout@v1
      - name: Download jar
        uses: actions/download-artifact@v3
        with:
          name: project_jar
          path: ${{ github.workspace }}/docker
      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }}
          -p ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build Docker image
        run: |
          cd docker
          docker build --build-arg DD_API_KEY=${{ secrets.DATADOG_API_KEY }} -t $REPO:latest -t $REPO:${GITHUB_SHA::8} .
      - name: Publish Docker image with commit sha tag
        run: docker push $REPO:${GITHUB_SHA::8}
      - name: Publish Docker image with tag latest
        run: docker push $REPO:latest
  deploy:
    needs: [ docker ]
    env:
      REPO: ${{ secrets.DOCKER_REPO }}
      RESOURCE_GROUP: ${{ secrets.AZURE_RESOURCE_GROUP_NAME }}
      APP_NAME: ${{ secrets.AZURE_CONTAINER_APP_NAME }}
    runs-on: ubuntu-latest
    steps:
      - name: 'Az CLI login'
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: 'Update containerapp image'
        run: |
          az extension add --name containerapp
          az containerapp update --name $APP_NAME --resource-group $RESOURCE_GROUP --image $REPO:${GITHUB_SHA::8}